.github/workflows/check-code.yml
.github/workflows/check-docs.yml
.github/workflows/check-package.yml

- [n/a] Did you write any new necessary tests?
Improves usability of reusable workflows.

Add names to all steps in reusable workflows

---

.github/workflows/check-package.yml

- [kind of yes] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [n/a] Did you write any new necessary tests?
Addresses a TODO item.
Will be very useful to skip certain OS/versions from caller workflows since some projects might not be incompatible, for example, with certain OS and Python versions.

Parameterise OS and Python versions for reusable workflows

---

.github/dependabot.yml

Updates the frequency to make it consistent with other repositories.

Increase dependabot frequency from monthly to weekly

---

.github/workflows/check-code.yml
README.md
src/pl_devtools/__about__.py
src/pl_devtools/imports.py
tests/unittests/test_imports.py

Add import utilities

---

.pre-commit-config.yaml
setup.cfg

See title
Unblocks CI failure in https://github.com/Lightning-AI/utilities/pull/32

Update lint config to match Lightning's

---

.github/workflows/publish-pypi.yml

Adding publishing workflow
**Todo:**

CI/CD: add publish workflow

---

src/lightning_utilities/__about__.py

Update version to 0.2.0 for a release

---

src/lightning_utilities/core/overrides.py
tests/unittests/core/test_overrides.py

Fixes https://github.com/Lightning-AI/utilities/issues/25

Copy over `is_overridden`

---

src/lightning_utilities/__about__.py

Update version for a 0.3.0 release

---

.github/actions/pip-list/action.yml
.github/workflows/check-code.yml
.github/workflows/check-docs.yml
.github/workflows/ci-testing.yml
.github/workflows/ci-use-checks.yml
.github/workflows/docs-deploy.yml

- [n/a] Did you write any new necessary tests?
See title.
Utilises https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/.

CI: pip list action

---

src/lightning_utilities/core/imports.py
tests/unittests/core/test_imports.py

Fixes https://github.com/Lightning-AI/utilities/issues/52

Provide installation instructions in `RequirementCache` error message

---

setup.py

Fix requirements parsing

---

.github/workflows/check-code.yml
.github/workflows/check-docs.yml
.github/workflows/check-package.yml
.github/workflows/check-schema.yml
.github/workflows/ci-testing.yml
.github/workflows/deploy-docs.yml
.github/workflows/publish-pypi.yml

Updates checkout actions to also include submodules if available.

ci: checkout submodules recursive

---

.github/actions/cache/action.yml
.github/actions/unittesting/action.yml
.github/workflows/cron-clear-cache.yml

refactor to use outputs to reduce interaction with Env. variables

ci: using outputs & cache dispatch

---

CHANGELOG.md

Add missing changelog for #86

---

requirements/base.txt
src/lightning_utilities/__about__.py

as changed in #76 and discovered in https://github.com/Lightning-AI/lightning/pull/16476#issuecomment-1402373282
so we can re-release with post suffix

lower min `packaging` version

---

.github/actions/pkg-create/action.yml
CHANGELOG.md

building the package with `python -m build`

ci: build package

---

CHANGELOG.md
src/lightning_utilities/core/requirements.py
src/lightning_utilities/install/__init__.py
src/lightning_utilities/install/requirements.py

porting https://github.com/Lightning-AI/lightning/pull/13912
so we can use it also in other projects like TM

adding requirements parser

---

src/lightning_utilities/__init__.py
src/lightning_utilities/core/__init__.py

<details>
</details>
Unblocks https://github.com/Lightning-AI/lightning/pull/16981#discussion_r1128175395

Make `apply_to_collection` importable from top level

---

.github/actions/cache/action.yml
.github/actions/pkg-install/action.yml
.github/workflows/check-docs.yml
.github/workflows/check-package.yml
.github/workflows/deploy-docs.yml

<details>
</details>
adding default Torch CPU download to speed up the check
plus some other minor cleaning... :chipmunk: 

ci: update & defaults

---

scripts/adjust-torch-versions.py

<details>
</details>
then we can just maintain single location not update all reports

add requirements script

---

.github/workflows/ci-use-checks.yaml

<details>
</details>
adding sample of such matrix

ci: custom pkg matrix

---

.github/actions/pkg-install/action.yml
CHANGELOG.md
scripts/adjust-torch-versions.py

<details>
</details>
the flags was mess up names...

ci: fix passing install flags

---

scripts/adjust-torch-versions.py

<details>
</details>
Needed during CI in this PR https://github.com/Lightning-AI/torchmetrics/pull/1792

Add torchaudio to adjust script

---

docs/source/conf.py
requirements/docs.txt

<details>
</details>
bump to almost the latest and fro diff from #142

bump sphinx

---

.pre-commit-config.yaml
pyproject.toml
setup.py
src/lightning_utilities/__init__.py
src/lightning_utilities/core/apply_func.py
src/lightning_utilities/core/enums.py
src/lightning_utilities/install/__init__.py
src/lightning_utilities/install/requirements.py
tests/unittests/core/test_apply_func.py
tests/unittests/core/test_imports.py
tests/unittests/core/test_overrides.py
tests/unittests/core/test_rank_zero.py
tests/unittests/mocks.py
tests/unittests/test/test_warnings.py

<details>
</details>
Copying the same configs from TorchMetrics

ruff: Isort and more

---

.github/workflows/check-docs.yml

<details>
</details>
Enable just running docs build not all doctests even if it is encouraged :chipmunk: 

ci: split running tests with docs

---

src/lightning_utilities/docs/formatting.py

<details>
</details>
reduce duplicate utility across all our projects

add `_linkcode_resolve` for docs

---

.github/scripts/find-unused-caches.py
.pre-commit-config.yaml
pyproject.toml
src/lightning_utilities/core/apply_func.py
src/lightning_utilities/core/enums.py
src/lightning_utilities/core/imports.py
src/lightning_utilities/core/rank_zero.py
src/lightning_utilities/docs/formatting.py
src/lightning_utilities/docs/retriever.py
src/lightning_utilities/install/requirements.py

<details>
</details>
standardize the docs formatting along lighning

precommit: enable docformatter

---

.codecov.yml
.github/actions/cache/action.yml
.github/actions/pip-list/action.yml
.github/actions/pkg-create/action.yml
.github/actions/pkg-install/action.yml
.github/actions/unittesting/action.yml
.github/markdown.links.config.json
.github/mergify.yml
.github/workflows/check-code.yml
.github/workflows/check-docs.yml
.github/workflows/check-md-links.yml
.github/workflows/check-package.yml
.github/workflows/check-schema.yml
.github/workflows/ci-testing.yml
.github/workflows/ci-use-checks.yaml
.github/workflows/cleanup-caches.yml
.github/workflows/cron-clear-cache.yml
.github/workflows/deploy-docs.yml
.github/workflows/release-pypi.yml
.pre-commit-config.yaml
.prettierignore
docs/source/_static/copybutton.js

<details>
</details>
standartize the YAML formatting

precommit: enable prettier

---

.github/labeler-config.yml
.github/workflows/label-pr.yml
.pre-commit-config.yaml

<details>
</details>
seems we had config but missed the action to operate it...

fix labelling PRs by change

---

scripts/adjust-torch-versions.py

<details>
</details>
note 2.1 is reeased

rolling versions after PT 2.1

---

.github/workflows/check-docs.yml
CHANGELOG.md

<details>
</details>
Allows to use that workflow also for building pdf docs and other targets

Allow Other targets than html for docs

---

.github/workflows/check-docs.yml
.github/workflows/ci-use-checks.yaml
CHANGELOG.md

<details>
</details>
Adds latexmk for the `latexpdf` target

Add latex dependency

---

scripts/adjust-torch-versions.py

<details>
</details>
following release of https://github.com/pytorch/pytorch/releases/tag/v2.1.1
----
:books: Documentation preview :books:: https://lit-utilities--192.org.readthedocs.build/en/192/

bump: script update with PT 2.1.1

---

.github/workflows/check-precommit.yml
.github/workflows/check-typing.yml
.github/workflows/ci-use-checks.yaml
CHANGELOG.md

<details>
</details>
typing is not used in many repos and for private repos it is handy to automate pre-commit on PR
----
:books: Documentation preview :books:: https://lit-utilities--191.org.readthedocs.build/en/191/

ci: split code checks & enable precommit updates

---

.github/workflows/check-precommit.yml
CHANGELOG.md

<details>
</details>
debugging: 
```
Started: bash /home/runner/work/_actions/actions-js/push/v1.4/start.sh
Push to branch ci/precommit
[ci/precommit d98cb32] pre-commit: running and fixing...
1 file changed, 1 deletion(-)
To https://github.com/Lightning-AI/sphinx-theme.git
! [remote rejected] HEAD -> ci/precommit (refusing to allow a GitHub App to create or update workflow `.github/workflows/code-lint.yml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/Lightning-AI/sphinx-theme.git'
Error: Invalid status code: 1
at ChildProcess.<anonymous> (/home/runner/work/_actions/actions-js/push/v1.4/start.js:9:[19](https://github.com/Lightning-AI/sphinx-theme/actions/runs/689424 …
```

ci/precommit: checkout with token

---

scripts/adjust-torch-versions.py

<details>
</details>
----
📚 Documentation preview 📚: https://lit-utilities--211.org.readthedocs.build/en/211/

Update version dict with newest version of torch packages

---

.pre-commit-config.yaml
pyproject.toml
scripts/adjust-torch-versions.py
src/lightning_utilities/cli/__main__.py
src/lightning_utilities/core/apply_func.py
src/lightning_utilities/core/rank_zero.py

<details>
</details>
following our main repos
----
📚 Documentation preview 📚: https://lit-utilities--230.org.readthedocs.build/en/230/

lint: switch Black to `ruff-format`

---

.pre-commit-config.yaml
pyproject.toml

<details>
</details>
some more config cleaning...
----
📚 Documentation preview 📚: https://lit-utilities--235.org.readthedocs.build/en/235/

lint: add pyproject formatting

---

scripts/adjust-torch-versions.py

<details>
</details>
regular update after new PT was released :)
----
📚 Documentation preview 📚: https://lit-utilities--248.org.readthedocs.build/en/248/

bump: script update with PT `2.2.2`

---

docs/source/conf.py
src/lightning_utilities/docs/formatting.py

<details>
</details>
adding some common functionality...
----
📚 Documentation preview 📚: https://lit-utilities--263.org.readthedocs.build/en/263/

docs: use iternal `_linkcode_resolve`

---

CHANGELOG.md
src/lightning_utilities/core/imports.py
src/lightning_utilities/install/requirements.py
tests/unittests/core/test_imports.py

Fixes #119
----
📚 Documentation preview 📚: https://lit-utilities--281.org.readthedocs.build/en/281/

Replace deprecated `pkg_resources`

---

CHANGELOG.md
src/lightning_utilities/__about__.py

To release latest changes.
----
📚 Documentation preview 📚: https://lit-utilities--282.org.readthedocs.build/en/282/

Bump version to 0.11.4 for release

---

.github/actions/pkg-install/action.yml
.github/workflows/check-package.yml
.github/workflows/ci-use-checks.yaml
CHANGELOG.md

<details>
</details>
Clarify misleading argument name
----
📚 Documentation preview 📚: https://lit-utilities--287.org.readthedocs.build/en/287/

ci: rename `import-extras` to `custom-import`

---

.github/workflows/cron-clear-cache.yml

<details>
</details>
input strings need to be converted to numbers
https://docs.github.com/en/enterprise-cloud@latest/actions/writing-workflows/choosing-what-your-workflow-does/expressions#example-returning-a-json-object
----
📚 Documentation preview 📚: https://lit-utilities--297.org.readthedocs.build/en/297/

ci/cron: fix inputs

---

.github/workflows/check-package.yml
.pre-commit-config.yaml
CHANGELOG.md

<details>
</details>
in some special vases user need to pass come cofig...
----
📚 Documentation preview 📚: https://lit-utilities--317.org.readthedocs.build/en/317/

ci: enable custom env. vars in pkg check

---

.github/workflows/ci-scripts.yml
.github/workflows/ci-testing.yml
.github/workflows/ci-use-checks.yaml

<details>
</details>
unblock CI
----
📚 Documentation preview 📚: https://lit-utilities--322.org.readthedocs.build/en/322/

ci: bump deprecated mac version

---

.github/actions/unittesting/action.yml
.github/workflows/check-docs.yml
.github/workflows/check-typing.yml
.github/workflows/ci-testing.yml
.github/workflows/ci-use-checks.yaml
CHANGELOG.md

<details>
</details>
re-creating #219 based on instructions in https://github.com/actions/upload-artifact/issues/480#issuecomment-2230044897
----
📚 Documentation preview 📚: https://lit-utilities--345.org.readthedocs.build/en/345/

ci: bump upload/download artifact `v4` [2/2] & `actions-ref` optional

---

.github/workflows/check-package.yml

<details>
</details>
freeze for 6.0 before we resolve:
```
Checking dist/lightning_utilities-0.12.0.dev0-py3-none-any.whl: ERROR    InvalidDistribution: Invalid distribution metadata: unrecognized or    
malformed field 'license-file'   
```
----
📚 Documentation preview 📚: https://lit-utilities--356.org.readthedocs.build/en/356/

ci: pin version for pkg check

---

.github/workflows/check-schema.yml
CHANGELOG.md

<details>
</details>
unblock Azure actions check, failing with new versions

ci: add `azure-schema-version`

---

scripts/run_standalone_tests.sh

<details>
</details>
porting https://github.com/Lightning-AI/pytorch-lightning/pull/20633 to be reused in other projects
----
📚 Documentation preview 📚: https://lit-utilities--374.org.readthedocs.build/en/374/

add generic testing for standalone

---

CHANGELOG.md
src/lightning_utilities/core/rank_zero.py

<details>
</details>
does not work for py3.10+
----
📚 Documentation preview 📚: https://lit-utilities--375.org.readthedocs.build/en/375/

fix python version parsing for stacklevel

---

.github/workflows/check-schema.yml
CHANGELOG.md

<details>
</details>
Fixes `Error: No file in /home/runner/work/base-images/base-images matched to [**/requirements.txt or **/pyproject.toml], make sure you have checked out the target repository`
----
📚 Documentation preview 📚: https://lit-utilities--376.org.readthedocs.build/en/376/

ci: fix using schema action

---

requirements/_docs.txt

<details>
</details>
remove old packages which are not much needed...
----
📚 Documentation preview 📚: https://lit-utilities--379.org.readthedocs.build/en/379/

docs: fix building rtfd

---

.github/actions/cache/action.yml
.github/scripts/find-unused-caches.py
.github/scripts/find-unused-caches.txt
.github/workflows/ci-use-checks.yaml
CHANGELOG.md
pyproject.toml
requirements/cli.txt
requirements/typing.txt
scripts/adjust-torch-versions.py
scripts/inject-selector-script.py
src/lightning_utilities/cli/__main__.py

<details>
</details>
We have dropped Fire with other projects
----
📚 Documentation preview 📚: https://lit-utilities--371.org.readthedocs.build/en/371/

switch CLI from `fire` to `jsonargparse`

---

CHANGELOG.md
scripts/run_standalone_tests.sh

<details>
</details>
Prevent false negative signal from testing...
----
📚 Documentation preview 📚: https://lit-utilities--383.org.readthedocs.build/en/383/

update coverage the standalone script

---

.pre-commit-config.yaml

<details>
</details>
the original was archived and laos keeps bumping to a alpha release :(
----
📚 Documentation preview 📚: https://lit-utilities--396.org.readthedocs.build/en/396/

ci/linter: switch to alternative `JoC0de/pre-commit-prettier`

---

src/lightning_utilities/core/apply_func.py

<details>
</details>
Fixes #405 .
----
📚 Documentation preview 📚: https://lit-utilities--406.org.readthedocs.build/en/406/

reorder type checking for collections in `_apply_to_collection_slow`

---

.github/workflows/check-md-links.yml
CHANGELOG.md

<details>
</details>
porting suggestion from https://github.com/Lightning-AI/pytorch-lightning/pull/20979
----
📚 Documentation preview 📚: https://lit-utilities--416.org.readthedocs.build/en/416/

ci: relax `markdown-link-check`

---

.github/workflows/check-package.yml
.github/workflows/ci-scripts.yml
.github/workflows/ci-testing.yml
CHANGELOG.md
pyproject.toml
requirements/cli.txt
src/lightning_utilities/cli/dependencies.py
tests/unittests/cli/test_dependencies.py

<details>
</details>
needed for https://github.com/Lightning-AI/litLogger/pull/177#issuecomment-3052534646
also will be used in LitServe or LitData
----
📚 Documentation preview 📚: https://lit-utilities--414.org.readthedocs.build/en/414/

CLI: replace min dependencies also in `pyproject. toml`

---

.github/scripts/find-unused-caches.py
scripts/adjust-torch-versions.py
scripts/inject-selector-script.py

<details>
</details>
improve feedback/UX for native python
----
📚 Documentation preview 📚: https://lit-utilities--418.org.readthedocs.build/en/418/

fix simple scripts for `sys.argv`

---

CHANGELOG.md
src/lightning_utilities/cli/dependencies.py
tests/unittests/cli/test_dependencies.py

<details>
</details>
Enable replace script like https://github.com/Lightning-AI/litLogger/blob/main/.github/scripts/replace-pyproject-dependency-package.py
----
📚 Documentation preview 📚: https://lit-utilities--423.org.readthedocs.build/en/423/

CLI: replace dependencies also in `pyproject.toml`
