Lightning-AI/utilities

- src/pl_devtools/imports.py
The app definition had these, but not the PL definition.
They are probably good. So let's add them
> Add import caches

- README.md
- docs/source/_templates/theme_variables.jinja
- setup.py
- src/lightning_tools/__about__.py
Fixes https://github.com/Lightning-AI/utilities/pull/27#discussion_r961673177
> Fix repo link

- .github/actions/cache/action.yml
- .github/workflows/clear-cache.yml
- .github/workflows/schedule-clear-cache.yml
- [:eyes:] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
Adds a reusable workflow that clears caches match with the given pattern.
```yml
name: Clear cache weekly
on:
schedule:
- cron: "0 0 * * 0"
jobs:
clear-cache:
uses: Lightning-AI/utilities/.github/workflows/clear-cache.yml@v9.9.9
with:
pattern: 'pip|conda|docs'  # remove caches whose key includes any of the strings (`pip`, `conda`, and `docs`).
```
or anther example here: https://github.com/Lightning-AI/lightning/pull/14593
I think this will be very nice as we can simplify workflows by removing the logic around weekly cache reset (like `env.TIME_PERIOD`) from workflow files.
If we didn't discuss your PR in Github …
> CI: Add reusable workflow to clear caches within a repository

- .github/workflows/check-schema.yml
Without `-v`, error messages almost have no information.
> CI: increase verbosity and comment schema file location

- .github/workflows/check-package.yml
- src/lightning_utilities/test/warning.py
- tests/unittests/test/test_warnings.py
Note: The implementation had to be changed because `pytest.warns(None)` is deprecated.
> Add `lightning_utilities.test.warning.no_warning_call`

- Makefile
For now, `make test` produces the error as followings:
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...] __main__.py: error: unrecognized arguments: --flake8
Removing `--flake8` can fix the error, just as with https://github.com/Lightning-AI/lightning/blob/master/Makefile#L39
Make sure you had fun coding 😄
> remove `--flake8` from `make test`

- src/lightning_utilities/core/imports.py
- tests/unittests/core/test_imports.py
- [n/a] Did you make sure to update the docs?
Fixes #59
> Added get_dependency_min_version_spec function

- src/lightning_utilities/core/imports.py
- tests/unittests/core/test_imports.py
This PR adds the ability to lazily import modules so that they are not actually imported until their first reference
> Add method to lazily import modules

- CHANGELOG.md
- src/lightning_utilities/__about__.py
- src/lightning_utilities/core/imports.py
- tests/unittests/core/test_imports.py
Adding a handy wrapper to provide better user error...
> add requires wrapper

- .github/workflows/check-package.yml
- .github/workflows/ci-testing.yml
- .github/workflows/ci-use-checks.yml
- CHANGELOG.md
- requirements/base.txt
- src/lightning_utilities/__init__.py
- src/lightning_utilities/core/__init__.py
turned out that this package may have have missing dependency `packaging`
> Fix & extend pkg install check

- .github/actions/cache/action.yml
- .github/actions/unittesting/action.yml
- .github/workflows/check-code.yml
- .github/workflows/check-docs.yml
- .github/workflows/check-package.yml
- .github/workflows/check-schema.yml
- .github/workflows/ci-testing.yml
- .github/workflows/clear-cache.yml
- .github/workflows/docs-deploy.yml
- .github/workflows/publish-pypi.yml
add names to all uses in actions
> add names for uses & norm spaces

- CHANGELOG.md
- src/lightning_utilities/core/apply_func.py
- tests/unittests/core/test_apply_func.py
<details>
Docstring, yes.
No, some tests were broken even without my changes. However, all tests in [`test_apply_func.py`](https://github.com/Lightning-AI/utilities/blob/d8f0b17e9ce64ec81caa514b3cd9d5301414c13a/tests/unittests/core/test_apply_func.py), including my new one, passed.
</details>
Allow frozen dataclasses to be ignored in `apply_to_collection`. This is useful to allow ignoring values which we never cared about anyway, [for example when using `apply_to_collection` to move data to a device](https://github.com/Lightning-AI/lightning/blob/1b1241ceb12fce0e30b4eb8bdb54779995a42e0a/src/lightning/fabric/utilities/optimizer.py#L34).
This (combined with a change in the previously linked line, see [main …
> Allow frozen dataclasses in `apply_to_collection`

- CHANGELOG.md
- src/lightning_utilities/core/enums.py
<details>
</details>
While extending, I found a bug that `source="key"` was not followed correctly
the idea coming from: https://github.com/Lightning-AI/metrics/pull/1474#discussion_r1094598260
> fix & extend `StrEnum.from_str`

- .github/workflows/check-package.yml
- .github/workflows/ci-testing.yml
- CHANGELOG.md
This aggrebates all parametrization, so you do not need to frequently change required checks when update matrix and you expect all shall pass
> ci: guardian as closure

- CHANGELOG.md
- src/lightning_utilities/core/imports.py
- tests/unittests/core/test_imports.py
Address https://github.com/Lightning-AI/lightning/pull/16607#pullrequestreview-1307506923
> More resillient `RequirementCache` that checks for module importability

- .github/workflows/release-pypi.yml
the trigger is tag and release so we upload only on release but the publish was passing on both event...
- https://github.com/Lightning-AI/utilities/actions/runs/4248017982
- https://github.com/Lightning-AI/utilities/actions/runs/4248017979 
> ci: remove duplicate try to publish

- .pre-commit-config.yaml
- pyproject.toml
- src/lightning_utilities/cli/dependencies.py
- src/lightning_utilities/core/apply_func.py
- src/lightning_utilities/core/enums.py
- tests/unittests/core/test_apply_func.py
- tests/unittests/core/test_enums.py
- tests/unittests/core/test_imports.py
- tests/unittests/test/test_warnings.py
<details>
</details>
improve code health
> ruff: C4-PT-RET-SIM

- src/lightning_utilities/core/imports.py
- src/lightning_utilities/core/rank_zero.py
Right now, using these decorators essentially eases the type signature of the functions they are applied to (since the output type is just `Callable[..., Any]`. But by making these functions generic, we can correctly preserve the type signatures involved.
> Do not erase function types in decorators

- CHANGELOG.md
- src/lightning_utilities/core/overrides.py
- tests/unittests/core/test_overrides.py
This is causing false positives in https://github.com/Lightning-AI/lightning/blob/01b82e4fb19943514594267e9b997ce96bb92f0c/src/lightning/pytorch/trainer/trainer.py#L1095
> Fix `is_overridden` with `@contextmanager`

- src/lightning_utilities/core/apply_func.py
Avoids graph breaks when `apply_to_collection` is called with simple inputs
> Fast paths for the common apply_to_collection inputs

- .github/actions/pkg-install/action.yml
- .github/scripts/find-unused-caches.txt
- .github/workflows/check-code.yml
- .pre-commit-config.yaml
- CHANGELOG.md
- pyproject.toml
- src/lightning_utilities/cli/dependencies.py
- src/lightning_utilities/core/imports.py
- src/lightning_utilities/docs/retriever.py
- tests/unittests/docs/test_retriever.py
<details>
</details>
hunting typos
> precommit: enable codespell

- .github/workflows/check-md-links.yml
- .github/workflows/ci-use-checks.yaml
- CHANGELOG.md
<details>
</details>
limit the check on PR just for changed files to not block contributions for unrelated changes 
> ci: expose base branch & narrow scope for md links

- CHANGELOG.md
- src/lightning_utilities/core/rank_zero.py
- tests/unittests/core/test_rank_zero.py
When using `rank_zero_only`, one might want to return a default object to avoid type errors on non-zero ranks.
Implemented in https://github.com/Lightning-AI/lightning/pull/18848/files#diff-ac4de1893b3d5f27cf2fb2c29c4fffbeee29c7e8bf42c101d5366867fff79ac0R56-R77
----
:books: Documentation preview :books:: https://lit-utilities--187.org.readthedocs.build/en/187/
> Add `rank_zero_only(..., default=)` argument

- src/lightning_utilities/core/apply_func.py
- tests/unittests/core/test_apply_func.py
…lection`.
<details>
</details>
Fixes #196 fixes #206 
----
📚 Documentation preview 📚: https://lit-utilities--210.org.readthedocs.build/en/210/
> Avoid accidental namedtuple conversion in `apply_to_collection`

- pyproject.toml
- tests/unittests/conftest.py
- tests/unittests/docs/test_retriever.py
<details>
</details>
make the real docs as copy so it does not pollute codebase
----
📚 Documentation preview 📚: https://lit-utilities--237.org.readthedocs.build/en/237/
> tests: refactor test_retriever with `temp_docs` fixture

- CHANGELOG.md
- docs/source/conf.py
- requirements/_docs.txt
- src/lightning_utilities/docs/__init__.py
- src/lightning_utilities/docs/formatting.py
- tests/unittests/docs/test_formatting.py
- tests/unittests/docs/test_retriever.py
<details>
</details>
Implementing https://github.com/Lightning-AI/pytorch-lightning/pull/19550#discussion_r1507751217
----
📚 Documentation preview 📚: https://lit-utilities--236.org.readthedocs.build/en/236/
> docs: pin version in links to external docs

- CHANGELOG.md
- src/lightning_utilities/docs/formatting.py
<details>
</details>
Fixes https://github.com/Lightning-AI/torchmetrics/actions/runs/8345953413/job/22842066217
use bu defaul request to PyPI and if not public package use local import
----
📚 Documentation preview 📚: https://lit-utilities--243.org.readthedocs.build/en/243/
> docs: fix/use PyPI versions for pinning

- .github/workflows/check-package.yml
- .github/workflows/ci-use-checks.yaml
- CHANGELOG.md
<details>
</details>
allowing to change python version for package building with some default
----
📚 Documentation preview 📚: https://lit-utilities--244.org.readthedocs.build/en/244/
> ci: enable setting python version for package build

- CHANGELOG.md
- docs/source/conf.py
- src/lightning_utilities/docs/formatting.py
<details>
</details>
debugging https://readthedocs.org/projects/lit-utilities/builds/23859566/
seems like `https://pytorch.org/docs/stable/objects.inv` is not the same as `https://pytorch.org/docs/1.26/objects.inv` even this is the latest at this time
----
📚 Documentation preview 📚: https://lit-utilities--245.org.readthedocs.build/en/245/
> docs: do not replace link for self

- CHANGELOG.md
- docs/source/index.rst
- docs/source/test-page.rst
- src/lightning_utilities/docs/formatting.py
- tests/unittests/docs/test_formatting.py
<details>
</details>
addressing #243 when package name is not trivial
discovered in https://github.com/Lightning-AI/torchmetrics/pull/2476
----
📚 Documentation preview 📚: https://lit-utilities--247.org.readthedocs.build/en/247/
> docs: fix parsing non-trivial package name

- src/lightning_utilities/__about__.py
- src/lightning_utilities/core/imports.py
- tests/unittests/core/test_imports.py
In #281 I made the implementation for RequirementCache to not depend on `pkg_resources`, but this accidentally broke checks against extras. For example:
```py
RequirementCache("jsonargparse[signatures]") 
```
would currently return true regardless of whether the signatures dependencies are installed or not. This is because `pkg_resources` was previously handling this directly. This PR brings this functionality back. Hopefully there are no other breakages. 
----
📚 Documentation preview 📚: https://lit-utilities--283.org.readthedocs.build/en/283/
> Fix extras check in RequirementCache

- .github/workflows/check-typing.yml
- CHANGELOG.md
<details>
</details>
```
mypy
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/Lightning-AI/lightning-app/actions/runs/9991062745/job/27613090126?pr=979#step:8:3).9.19/x64
PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.9.19/x6[4](https://github.com/Lightning-AI/lightning-app/actions/runs/9991062745/job/27613090126?pr=979#step:8:4)/lib/pkgconfig
Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.19/x[6](https://github.com/Lightning-AI/lightning-app/actions/runs/9991062745/job/27613090126?pr=979#step:8:6)4
Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.19/x64
Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.19/x64 …
```
> ci: update mypy check

- CHANGELOG.md
- src/lightning_utilities/__about__.py
- src/lightning_utilities/core/imports.py
- tests/unittests/core/test_imports.py
When we replaced the deprecated `pkg_resources` version parsing in #281, we replaced the version comparison. The previous way implicitly handled pre-release version specifications, like `1.10.0.dev0+931b44f` for example. This functionality got accidentally lost (but wasn't tested before). This PR restores this so that we don't break version parsing. The added test fails on main.
Raised in https://github.com/Lightning-AI/lightning-thunder/issues/809
----
📚 Documentation preview 📚: https://lit-utilities--292.org.readthedocs.build/en/292/
> Fix parsing pre-release package versions

- .github/workflows/check-package.yml
- CHANGELOG.md
Closes #302. I referred to the last section of this migration guide: https://github.com/actions/upload-artifact/blob/b18b1d32f3f31abcdc29dee3f2484801fe7822f4/docs/MIGRATION.md
----
📚 Documentation preview 📚: https://lit-utilities--303.org.readthedocs.build/en/303/
> Pass `include-hidden-files: true` to `actions/upload-artifact`

- .github/workflows/ci-scripts.yml
- scripts/adjust-torch-versions.py
<details>
</details>
With this change we do not face critical CI failure after each Torch release and need of manual version bumping unless there is and exception
----
📚 Documentation preview 📚: https://lit-utilities--318.org.readthedocs.build/en/318/
> update script with dynamic torch-ecosystem versions determinations

- .github/actions/pkg-install/action.yml
- .github/workflows/check-package.yml
- .github/workflows/ci-use-checks.yaml
- CHANGELOG.md
<details>
</details>
make the default check for package import as optional
----
📚 Documentation preview 📚: https://lit-utilities--325.org.readthedocs.build/en/325/
> ci: split pkg check imports

- .codecov.yml
- .github/workflows/ci-cli.yml
- .github/workflows/ci-scripts.yml
- CHANGELOG.md
- MANIFEST.in
- src/lightning_utilities/cli/__main__.py
<details>
</details>
seems since #68 we have been missing CLI
----
📚 Documentation preview 📚: https://lit-utilities--332.org.readthedocs.build/en/332/
> fix: missing CLI

- .github/workflows/ci-cli.yml
- CHANGELOG.md
- src/lightning_utilities/cli/dependencies.py
<details>
</details>
----
📚 Documentation preview 📚: https://lit-utilities--333.org.readthedocs.build/en/333/
> cli: update parsing inputs

- .github/workflows/deploy-docs.yml
<details>
</details>
trying to resolve https://github.com/JamesIves/github-pages-deploy-action/issues/1753#issuecomment-2513932383
----
📚 Documentation preview 📚: https://lit-utilities--340.org.readthedocs.build/en/340/
> ci: update building docs

- .github/actions/pkg-create/action.yml
- .github/actions/pkg-install/action.yml
- .github/workflows/check-package.yml
- .github/workflows/ci-use-checks.yaml
- .github/workflows/deploy-docs.yml
- .github/workflows/release-pypi.yml
- CHANGELOG.md
<details>
</details>
re-creating #219 based on instructions in https://github.com/actions/upload-artifact/issues/480#issuecomment-2230044897
it also updated the workflows to be parallel, from
becoming
----
📚 Documentation preview 📚: https://lit-utilities--344.org.readthedocs.build/en/344/
> ci: bump upload/download artifact `v4` [1/2]

- pyproject.toml
- scripts/inject-selector-script.py
<details>
</details>
simplify the releasing process with automating replacement
----
📚 Documentation preview 📚: https://lit-utilities--349.org.readthedocs.build/en/349/
> script: inject version selector to HTML docs

- .github/actions/pkg-create/action.yml
- .github/actions/pkg-install/action.yml
- .github/workflows/check-package.yml
- .github/workflows/ci-use-checks.yaml
- CHANGELOG.md
- setup.py
<details>
</details>
[debugging](https://github.com/Lightning-AI/utilities/actions/runs/12349525363/job/34460588681) strange issue with unzip created package on another OS?
```
Traceback (most recent call last):
File "/home/runner/.local/bin/twine", line 8, in <module>
sys.exit(main())
File "/home/runner/.local/lib/python3.[10](https://github.com/Lightning-AI/utilities/actions/runs/12349525363/job/34460588681#step:3:11)/site-packages/twine/__main__.py", line 33, in main
error = cli.dispatch(sys.argv[1:])
File "/home/runner/.local/lib/python3.10/site-packages/twine/cli.py", line [12](https://github.com/Lightning-AI/utilities/actions/runs/12349525363/job/34460588681#step:3:13)9, in dispatch
return …
```
> ci: debug pkg create on multi-OS

- .github/workflows/check-schema.yml
- requirements/gha-schema.txt
<details>
</details>
need to be tested/validated on https://github.com/Lightning-AI/lightning-thunder/tree/main/.azure
trying to address
```
.azure/gpu-tests.yml
Error: schemafile was not valid
SchemaError: '^[^\\/~\\^\\: \\[\\]\\\\]+(\\/[^\\/~\\^\\: \\[\\]\\\\]+)*$' is not a 'regex'
Failed validating 'format' in metaschema['properties']['definitions']['additionalProperties']['properties']['pattern']:
{'type': 'string', 'format': 'regex'}
On schema['definitions']['branchFilter']['pattern']:
'^[^\\/~\\^\\: \\[\\]\\\\]+(\\/[^\\/~\\^\\: \\[\\]\\\\]+)*$'
in "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/check_jsonschema/checker.py", line 56
>>> return self._schema_loader.get_validator( …
```
> ci: update azure-pipelines schema

- CHANGELOG.md
- src/lightning_utilities/core/apply_func.py
- tests/unittests/core/test_apply_func.py
- tests/unittests/mocks.py
<details>
</details>
Fixes #279 
----
📚 Documentation preview 📚: https://lit-utilities--363.org.readthedocs.build/en/363/
> fix: resetting dataclass's `cached_property` once `apply_to_collection` is called

- .github/workflows/ci-use-checks.yaml
- .github/workflows/deploy-docs.yml
<details>
</details>
this installations now takes 20min and it not really need
https://github.com/Lightning-AI/utilities/actions/runs/13542003974/job/37844965854?pr=363
----
📚 Documentation preview 📚: https://lit-utilities--365.org.readthedocs.build/en/365/
> ci: drop unused latext install for docs

- .github/workflows/check-schema.yml
- CHANGELOG.md
<details>
</details>
Addressing discovery in https://github.com/python-jsonschema/check-jsonschema/pull/552
----
📚 Documentation preview 📚: https://lit-utilities--384.org.readthedocs.build/en/384/
> ci: fix parsing Azure schema

- .github/workflows/check-package.yml
<details>
</details>
address some long installation
----
📚 Documentation preview 📚: https://lit-utilities--412.org.readthedocs.build/en/412/
> CI: make timeout configurable for install jobs in check-package.yml

- CHANGELOG.md
- src/lightning_utilities/cli/__main__.py
- tests/unittests/cli/test_command_line.py
<details>
</details>
Adding tests and fixing #371
----
📚 Documentation preview 📚: https://lit-utilities--420.org.readthedocs.build/en/420/
> cli: debug optional args
